"use client";
import {useState} from "react";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {createClient} from "@/lib/supabase/browser";
import {OrbitLogo} from "../../components/OrbitLogo";
import RotatingGlobe from "../../components/RotatingGlobe";
export default function SignUp(){
 const [username,setUsername]=useState("");const [name,setName]=useState("");const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [phone,setPhone]=useState("");const [mode,setMode]=useState<"email"|"phone">("email");const [msg,setMsg]=useState("");const [busy,setBusy]=useState(false);const router=useRouter();
 const google=async()=>{const s=createClient();const {error}=await s.auth.signInWithOAuth({provider:"google",options:{redirectTo:`${window.location.origin}/auth/callback`}});if(error)setMsg(error.message)};
 const submit=async()=>{setBusy(true);setMsg("");const s=createClient();try{if(!/^[a-z0-9_]{3,24}$/.test(username))throw new Error("Username must be 3–24 characters: letters, numbers or underscore.");if(mode==="email"){const {data,error}=await s.auth.signUp({email,password,options:{data:{username,full_name:name}}});if(error)throw error;if(data.session)router.push("/");else setMsg("Account created. Check your email to confirm your ORBIT account.");}else{const {data,error}=await s.auth.signUp({phone,password,options:{data:{username,full_name:name}}});if(error)throw error;if(data.session)router.push("/");else setMsg("OTP/phone confirmation is required. Complete the verification configured in Supabase.");}}catch(e){setMsg(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};
 return <main className="auth-page"><div className="auth-visual"><RotatingGlobe/></div><div className="auth-card"><Link href="/"><OrbitLogo/></Link><h1>Enter ORBIT.</h1><p className="muted">Create one identity for your asset lifecycle.</p><div className="method-tabs"><button className={mode==="email"?"active":""} onClick={()=>setMode("email")}>Email</button><button className={mode==="phone"?"active":""} onClick={()=>setMode("phone")}>Mobile</button><button onClick={google}>Google</button></div><div className="field"><label>ORBIT username</label><input value={username} onChange={e=>setUsername(e.target.value.toLowerCase())} placeholder="jay_orbit"/></div><div className="field"><label>Full name</label><input value={name} onChange={e=>setName(e.target.value)} placeholder="Your name"/></div>{mode==="email"?<div className="field"><label>Email</label><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></div>:<div className="field"><label>Mobile number</label><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+91 98XXXXXXXX"/></div>}<div className="field"><label>Password</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Create a strong password"/></div><button className="btn primary" style={{width:"100%"}} disabled={busy} onClick={submit}>{busy?"Creating…":"Create ORBIT account →"}</button><button className="btn google" onClick={google}>Continue directly with Google / Gmail</button>{msg&&<div className={msg.toLowerCase().includes("created")?"success":"error"}>{msg}</div>}<p className="muted" style={{fontSize:12,marginTop:18}}>Already have an account? <Link className="auth-link" href="/auth/login">Log in</Link></p></div></main>
}
