"use client";
import {useState} from "react";
import Link from "next/link";
import {OrbitLogo} from "../components/OrbitLogo";
import {createClient} from "@/lib/supabase/browser";

export default function Dashboard(){
 const [name,setName]=useState("");const [value,setValue]=useState("");const [reg,setReg]=useState("");const [msg,setMsg]=useState("");const [busy,setBusy]=useState(false);
 async function createAsset(){setBusy(true);setMsg("");try{const s=createClient();const {data:{user}}=await s.auth.getUser();if(!user)throw new Error("Please log in first.");const r=await fetch("/api/assets",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({asset_type:"Vehicle",name,declared_value_inr:Number(value||0),registration_ref:reg})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Could not create asset");setMsg(`Asset created: ${d.asset_code}`)}catch(e){setMsg(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 return <main><header className="top"><Link href="/"><OrbitLogo/></Link><Link className="btn" href="/">← Home</Link></header><section className="dashboard"><span className="pill">ORBIT WORKSPACE</span><h1>Asset command center.</h1><p className="muted">Register, verify and manage your real-world asset lifecycle.</p><div className="dashboard-grid" style={{marginTop:30}}><div className="dash-card"><small className="muted">MY ASSETS</small><h2>0</h2></div><div className="dash-card"><small className="muted">VERIFIED</small><h2>0</h2></div><div className="dash-card"><small className="muted">TRANSFERS</small><h2>0</h2></div></div><div className="auth-card" style={{maxWidth:720,marginTop:25}}><span className="pill">VEHICLE MVP</span><h2>Register your first vehicle</h2><div className="field"><label>Vehicle name</label><input value={name} onChange={e=>setName(e.target.value)} placeholder="2022 Honda City"/></div><div className="field"><label>Declared value (INR)</label><input value={value} onChange={e=>setValue(e.target.value)} placeholder="1000000" inputMode="numeric"/></div><div className="field"><label>Registration reference</label><input value={reg} onChange={e=>setReg(e.target.value)} placeholder="GJ01AB1234 / document reference"/></div><div className="notice">Raw ownership/KYC documents stay off-chain. ORBIT can later anchor hashes and verification events to a blockchain.</div><button className="btn primary" disabled={busy} onClick={createAsset}>{busy?"Creating…":"Create verified asset record →"}</button>{msg&&<div className={msg.startsWith("Asset")?"success":"error"}>{msg}</div>}</div></section></main>
}
